//******Do not modify this file********//
//******generated by program********//
#include "dla_interface_with_system.h"
#include "data_struct_define_share.h"
//////////////////////////////////

#include <stdio.h>
#include <stdlib.h>
//////////////////////////////////

memory_d* global_memory_d_array;
int global_memory_d_num;
int global_batch_input_num;
memory_d* global_batch_input_array;
memory_d* global_batch_output_array;
//////////////////////////////////

void init_global_var() {
	global_memory_d_num = 2;
	global_memory_d_array = (memory_d*) malloc (sizeof(memory_d) * 2);
	global_memory_d_array[0].memory_id = 0;
	global_memory_d_array[0].size = 10 + 4096;
	global_memory_d_array[0].phy_addr = (unsigned int) malloc (4106);
	if(global_memory_d_array[0].phy_addr == NULL) {
		printf("global_memory_d_array[0] malloc failed\n");
	}
	global_memory_d_array[0].aligned_phy_addr = (global_memory_d_array[0].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_memory_d_array[0].aligned_size = 10;
	global_memory_d_array[1].memory_id = 1;
	global_memory_d_array[1].size = 4096 + 4096;
	global_memory_d_array[1].phy_addr = (unsigned int) malloc (8192);
	if(global_memory_d_array[1].phy_addr == NULL) {
		printf("global_memory_d_array[1] malloc failed\n");
	}
	global_memory_d_array[1].aligned_phy_addr = (global_memory_d_array[1].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_memory_d_array[1].aligned_size = 4096;
//////////////////////////////////

	global_batch_input_array = (memory_d*) malloc (sizeof (memory_d) * 10);
	global_batch_output_array = (memory_d*) malloc (sizeof (memory_d) * 10);
//////////////////////////////////

	global_batch_input_array[0].memory_id = 0;
	global_batch_input_array[0].size = 10 + 4096;
	global_batch_input_array[0].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[0].phy_addr == NULL) {
		printf("global_batch_input_array[0] malloc failed\n");
	}
	global_batch_input_array[0].aligned_phy_addr = (global_batch_input_array[0].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[0].aligned_size = 10;
	global_batch_input_array[1].memory_id = 1;
	global_batch_input_array[1].size = 10 + 4096;
	global_batch_input_array[1].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[1].phy_addr == NULL) {
		printf("global_batch_input_array[1] malloc failed\n");
	}
	global_batch_input_array[1].aligned_phy_addr = (global_batch_input_array[1].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[1].aligned_size = 10;
	global_batch_input_array[2].memory_id = 2;
	global_batch_input_array[2].size = 10 + 4096;
	global_batch_input_array[2].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[2].phy_addr == NULL) {
		printf("global_batch_input_array[2] malloc failed\n");
	}
	global_batch_input_array[2].aligned_phy_addr = (global_batch_input_array[2].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[2].aligned_size = 10;
	global_batch_input_array[3].memory_id = 3;
	global_batch_input_array[3].size = 10 + 4096;
	global_batch_input_array[3].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[3].phy_addr == NULL) {
		printf("global_batch_input_array[3] malloc failed\n");
	}
	global_batch_input_array[3].aligned_phy_addr = (global_batch_input_array[3].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[3].aligned_size = 10;
	global_batch_input_array[4].memory_id = 4;
	global_batch_input_array[4].size = 10 + 4096;
	global_batch_input_array[4].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[4].phy_addr == NULL) {
		printf("global_batch_input_array[4] malloc failed\n");
	}
	global_batch_input_array[4].aligned_phy_addr = (global_batch_input_array[4].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[4].aligned_size = 10;
	global_batch_input_array[5].memory_id = 5;
	global_batch_input_array[5].size = 10 + 4096;
	global_batch_input_array[5].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[5].phy_addr == NULL) {
		printf("global_batch_input_array[5] malloc failed\n");
	}
	global_batch_input_array[5].aligned_phy_addr = (global_batch_input_array[5].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[5].aligned_size = 10;
	global_batch_input_array[6].memory_id = 6;
	global_batch_input_array[6].size = 10 + 4096;
	global_batch_input_array[6].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[6].phy_addr == NULL) {
		printf("global_batch_input_array[6] malloc failed\n");
	}
	global_batch_input_array[6].aligned_phy_addr = (global_batch_input_array[6].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[6].aligned_size = 10;
	global_batch_input_array[7].memory_id = 7;
	global_batch_input_array[7].size = 10 + 4096;
	global_batch_input_array[7].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[7].phy_addr == NULL) {
		printf("global_batch_input_array[7] malloc failed\n");
	}
	global_batch_input_array[7].aligned_phy_addr = (global_batch_input_array[7].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[7].aligned_size = 10;
	global_batch_input_array[8].memory_id = 8;
	global_batch_input_array[8].size = 10 + 4096;
	global_batch_input_array[8].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[8].phy_addr == NULL) {
		printf("global_batch_input_array[8] malloc failed\n");
	}
	global_batch_input_array[8].aligned_phy_addr = (global_batch_input_array[8].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[8].aligned_size = 10;
	global_batch_input_array[9].memory_id = 9;
	global_batch_input_array[9].size = 10 + 4096;
	global_batch_input_array[9].phy_addr = (unsigned int) malloc (4106);
	if(global_batch_input_array[9].phy_addr == NULL) {
		printf("global_batch_input_array[9] malloc failed\n");
	}
	global_batch_input_array[9].aligned_phy_addr = (global_batch_input_array[9].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_input_array[9].aligned_size = 10;
	global_batch_output_array[0].memory_id = 0;
	global_batch_output_array[0].size = 4096 + 4096;
	global_batch_output_array[0].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[0].phy_addr == NULL) {
		printf("global_batch_output_array[0] malloc failed\n");
	}
	global_batch_output_array[0].aligned_phy_addr = (global_batch_output_array[0].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[0].aligned_size = 4096;
	global_batch_output_array[1].memory_id = 1;
	global_batch_output_array[1].size = 4096 + 4096;
	global_batch_output_array[1].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[1].phy_addr == NULL) {
		printf("global_batch_output_array[1] malloc failed\n");
	}
	global_batch_output_array[1].aligned_phy_addr = (global_batch_output_array[1].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[1].aligned_size = 4096;
	global_batch_output_array[2].memory_id = 2;
	global_batch_output_array[2].size = 4096 + 4096;
	global_batch_output_array[2].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[2].phy_addr == NULL) {
		printf("global_batch_output_array[2] malloc failed\n");
	}
	global_batch_output_array[2].aligned_phy_addr = (global_batch_output_array[2].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[2].aligned_size = 4096;
	global_batch_output_array[3].memory_id = 3;
	global_batch_output_array[3].size = 4096 + 4096;
	global_batch_output_array[3].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[3].phy_addr == NULL) {
		printf("global_batch_output_array[3] malloc failed\n");
	}
	global_batch_output_array[3].aligned_phy_addr = (global_batch_output_array[3].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[3].aligned_size = 4096;
	global_batch_output_array[4].memory_id = 4;
	global_batch_output_array[4].size = 4096 + 4096;
	global_batch_output_array[4].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[4].phy_addr == NULL) {
		printf("global_batch_output_array[4] malloc failed\n");
	}
	global_batch_output_array[4].aligned_phy_addr = (global_batch_output_array[4].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[4].aligned_size = 4096;
	global_batch_output_array[5].memory_id = 5;
	global_batch_output_array[5].size = 4096 + 4096;
	global_batch_output_array[5].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[5].phy_addr == NULL) {
		printf("global_batch_output_array[5] malloc failed\n");
	}
	global_batch_output_array[5].aligned_phy_addr = (global_batch_output_array[5].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[5].aligned_size = 4096;
	global_batch_output_array[6].memory_id = 6;
	global_batch_output_array[6].size = 4096 + 4096;
	global_batch_output_array[6].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[6].phy_addr == NULL) {
		printf("global_batch_output_array[6] malloc failed\n");
	}
	global_batch_output_array[6].aligned_phy_addr = (global_batch_output_array[6].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[6].aligned_size = 4096;
	global_batch_output_array[7].memory_id = 7;
	global_batch_output_array[7].size = 4096 + 4096;
	global_batch_output_array[7].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[7].phy_addr == NULL) {
		printf("global_batch_output_array[7] malloc failed\n");
	}
	global_batch_output_array[7].aligned_phy_addr = (global_batch_output_array[7].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[7].aligned_size = 4096;
	global_batch_output_array[8].memory_id = 8;
	global_batch_output_array[8].size = 4096 + 4096;
	global_batch_output_array[8].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[8].phy_addr == NULL) {
		printf("global_batch_output_array[8] malloc failed\n");
	}
	global_batch_output_array[8].aligned_phy_addr = (global_batch_output_array[8].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[8].aligned_size = 4096;
	global_batch_output_array[9].memory_id = 9;
	global_batch_output_array[9].size = 4096 + 4096;
	global_batch_output_array[9].phy_addr = (unsigned int) malloc (8192);
	if(global_batch_output_array[9].phy_addr == NULL) {
		printf("global_batch_output_array[9] malloc failed\n");
	}
	global_batch_output_array[9].aligned_phy_addr = (global_batch_output_array[9].phy_addr + 0x1000 -1 ) & (~(0x1000-1));
	global_batch_output_array[9].aligned_size = 4096;

}